# Generated by Django 3.1.4 on 2021-04-05 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(upload_to='file/logo')),
                ('lang', models.CharField(choices=[('bangla', 'Bangla'), ('hindi', 'Hindi'), ('english', 'English'), ('tamil', 'Tamil')], default='Hindi', max_length=250)),
                ('title', models.CharField(max_length=250)),
                ('file', models.CharField(max_length=250)),
                ('banner', models.FileField(upload_to='file/banner')),
                ('trailer', models.CharField(max_length=250)),
                ('thumbnail', models.FileField(upload_to='file/thumbnail')),
                ('time', models.CharField(max_length=20)),
                ('production', models.CharField(max_length=50)),
                ('movie_genre', models.CharField(blank=True, choices=[('action', 'Action'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('comedy', 'Comedy'), ('sci-fi', 'Sci-Fi')], default='Drama', max_length=250)),
                ('category', models.CharField(choices=[('movie', 'Movie'), ('music_video', 'Music Video'), ('music_audio', 'Music Audio')], default='Music Video', max_length=250)),
                ('release', models.CharField(max_length=100)),
                ('starring', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='profile/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
