# Generated by Django 3.1.4 on 2021-04-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('new_releases', 'New_Releases'), ('recently_added', 'Recently_Added'), ('trending', 'Trending'), ('must_watch', 'Must_Watch')], default='Recently_Added', max_length=250),
        ),
    ]
